// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/group/element.proto

package group

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 加入成员的请求
type ElementAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection string   `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"` // 集合UUID
	Key        string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`               // 键
	Alias      string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`           // 别名
	Label      []string `protobuf:"bytes,4,rep,name=label,proto3" json:"label,omitempty"`           // 标签
}

func (x *ElementAddRequest) Reset() {
	*x = ElementAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementAddRequest) ProtoMessage() {}

func (x *ElementAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementAddRequest.ProtoReflect.Descriptor instead.
func (*ElementAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{0}
}

func (x *ElementAddRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ElementAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ElementAddRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ElementAddRequest) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

// 更新成员的请求
type ElementUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`   // 成员UUID
	Key   string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`     // 键
	Alias string   `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"` // 别名
	Label []string `protobuf:"bytes,4,rep,name=label,proto3" json:"label,omitempty"` // 标签
}

func (x *ElementUpdateRequest) Reset() {
	*x = ElementUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementUpdateRequest) ProtoMessage() {}

func (x *ElementUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementUpdateRequest.ProtoReflect.Descriptor instead.
func (*ElementUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{1}
}

func (x *ElementUpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ElementUpdateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ElementUpdateRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ElementUpdateRequest) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

// 列举成员的请求
type ElementListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset     int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`        // 偏移值
	Count      int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`          // 数量
	Collection string `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"` // 集合UUID, 空值时列举所有集合
}

func (x *ElementListRequest) Reset() {
	*x = ElementListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementListRequest) ProtoMessage() {}

func (x *ElementListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementListRequest.ProtoReflect.Descriptor instead.
func (*ElementListRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{2}
}

func (x *ElementListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ElementListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ElementListRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

// 搜索成员的请求
type ElementSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset     int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`        // 偏移值
	Count      int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`          // 数量
	Collection string `protobuf:"bytes,3,opt,name=collection,proto3" json:"collection,omitempty"` // 集合UUID, 空值时列举所有集合
	Key        string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`               // 键
	Alias      string `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`           // 别名
}

func (x *ElementSearchRequest) Reset() {
	*x = ElementSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementSearchRequest) ProtoMessage() {}

func (x *ElementSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementSearchRequest.ProtoReflect.Descriptor instead.
func (*ElementSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{3}
}

func (x *ElementSearchRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ElementSearchRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ElementSearchRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ElementSearchRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ElementSearchRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

// 列举成员的回复
type ElementListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Total  uint64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`  // 总数
	Entity []*ElementEntity `protobuf:"bytes,3,rep,name=entity,proto3" json:"entity,omitempty"` // 实体列表
}

func (x *ElementListResponse) Reset() {
	*x = ElementListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementListResponse) ProtoMessage() {}

func (x *ElementListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementListResponse.ProtoReflect.Descriptor instead.
func (*ElementListResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{4}
}

func (x *ElementListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ElementListResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ElementListResponse) GetEntity() []*ElementEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 移除成员的请求
type ElementRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 成员UUID
}

func (x *ElementRemoveRequest) Reset() {
	*x = ElementRemoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementRemoveRequest) ProtoMessage() {}

func (x *ElementRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementRemoveRequest.ProtoReflect.Descriptor instead.
func (*ElementRemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{5}
}

func (x *ElementRemoveRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取成员的请求
type ElementGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 成员uuid
}

func (x *ElementGetRequest) Reset() {
	*x = ElementGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementGetRequest) ProtoMessage() {}

func (x *ElementGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementGetRequest.ProtoReflect.Descriptor instead.
func (*ElementGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{6}
}

func (x *ElementGetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取成员信息的回复
type ElementGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Entity *ElementEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"` // 实体
}

func (x *ElementGetResponse) Reset() {
	*x = ElementGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementGetResponse) ProtoMessage() {}

func (x *ElementGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementGetResponse.ProtoReflect.Descriptor instead.
func (*ElementGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{7}
}

func (x *ElementGetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ElementGetResponse) GetEntity() *ElementEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 获取成员所在的集合的请求
type ElementWhereRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // 键
}

func (x *ElementWhereRequest) Reset() {
	*x = ElementWhereRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementWhereRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementWhereRequest) ProtoMessage() {}

func (x *ElementWhereRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementWhereRequest.ProtoReflect.Descriptor instead.
func (*ElementWhereRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{8}
}

func (x *ElementWhereRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// 获取成员所在的集合的回复
type ElementWhereResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                                                                     // 状态
	Uuid   map[string]string `protobuf:"bytes,2,rep,name=uuid,proto3" json:"uuid,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 在各集合中的UUID
}

func (x *ElementWhereResponse) Reset() {
	*x = ElementWhereResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_element_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementWhereResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementWhereResponse) ProtoMessage() {}

func (x *ElementWhereResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_element_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementWhereResponse.ProtoReflect.Descriptor instead.
func (*ElementWhereResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_element_proto_rawDescGZIP(), []int{9}
}

func (x *ElementWhereResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ElementWhereResponse) GetUuid() map[string]string {
	if x != nil {
		return x.Uuid
	}
	return nil
}

var File_proto_group_element_proto protoreflect.FileDescriptor

var file_proto_group_element_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x11,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22,
	0x68, 0x0a, 0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x62, 0x0a, 0x12, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x01,
	0x0a, 0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x80, 0x01, 0x0a,
	0x13, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x2c, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x2a, 0x0a, 0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x27, 0x0a, 0x11, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x12, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x2c, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x27, 0x0a, 0x13, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x68, 0x65, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xb1, 0x01, 0x0a, 0x14, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x57, 0x68, 0x65, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x68, 0x65, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x1a, 0x37, 0x0a, 0x09, 0x55, 0x75, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xc5, 0x03, 0x0a,
	0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x36, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12,
	0x18, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x3c, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e,
	0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x1b, 0x2e, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x1b,
	0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x05, 0x57, 0x68, 0x65, 0x72, 0x65, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x68, 0x65, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x68, 0x65, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x3b, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_group_element_proto_rawDescOnce sync.Once
	file_proto_group_element_proto_rawDescData = file_proto_group_element_proto_rawDesc
)

func file_proto_group_element_proto_rawDescGZIP() []byte {
	file_proto_group_element_proto_rawDescOnce.Do(func() {
		file_proto_group_element_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_group_element_proto_rawDescData)
	})
	return file_proto_group_element_proto_rawDescData
}

var file_proto_group_element_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_group_element_proto_goTypes = []interface{}{
	(*ElementAddRequest)(nil),    // 0: group.ElementAddRequest
	(*ElementUpdateRequest)(nil), // 1: group.ElementUpdateRequest
	(*ElementListRequest)(nil),   // 2: group.ElementListRequest
	(*ElementSearchRequest)(nil), // 3: group.ElementSearchRequest
	(*ElementListResponse)(nil),  // 4: group.ElementListResponse
	(*ElementRemoveRequest)(nil), // 5: group.ElementRemoveRequest
	(*ElementGetRequest)(nil),    // 6: group.ElementGetRequest
	(*ElementGetResponse)(nil),   // 7: group.ElementGetResponse
	(*ElementWhereRequest)(nil),  // 8: group.ElementWhereRequest
	(*ElementWhereResponse)(nil), // 9: group.ElementWhereResponse
	nil,                          // 10: group.ElementWhereResponse.UuidEntry
	(*Status)(nil),               // 11: group.Status
	(*ElementEntity)(nil),        // 12: group.ElementEntity
	(*UuidResponse)(nil),         // 13: group.UuidResponse
}
var file_proto_group_element_proto_depIdxs = []int32{
	11, // 0: group.ElementListResponse.status:type_name -> group.Status
	12, // 1: group.ElementListResponse.entity:type_name -> group.ElementEntity
	11, // 2: group.ElementGetResponse.status:type_name -> group.Status
	12, // 3: group.ElementGetResponse.entity:type_name -> group.ElementEntity
	11, // 4: group.ElementWhereResponse.status:type_name -> group.Status
	10, // 5: group.ElementWhereResponse.uuid:type_name -> group.ElementWhereResponse.UuidEntry
	0,  // 6: group.Element.Add:input_type -> group.ElementAddRequest
	1,  // 7: group.Element.Update:input_type -> group.ElementUpdateRequest
	2,  // 8: group.Element.List:input_type -> group.ElementListRequest
	3,  // 9: group.Element.Search:input_type -> group.ElementSearchRequest
	5,  // 10: group.Element.Remove:input_type -> group.ElementRemoveRequest
	6,  // 11: group.Element.Get:input_type -> group.ElementGetRequest
	8,  // 12: group.Element.Where:input_type -> group.ElementWhereRequest
	13, // 13: group.Element.Add:output_type -> group.UuidResponse
	13, // 14: group.Element.Update:output_type -> group.UuidResponse
	4,  // 15: group.Element.List:output_type -> group.ElementListResponse
	4,  // 16: group.Element.Search:output_type -> group.ElementListResponse
	13, // 17: group.Element.Remove:output_type -> group.UuidResponse
	7,  // 18: group.Element.Get:output_type -> group.ElementGetResponse
	9,  // 19: group.Element.Where:output_type -> group.ElementWhereResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_group_element_proto_init() }
func file_proto_group_element_proto_init() {
	if File_proto_group_element_proto != nil {
		return
	}
	file_proto_group_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_group_element_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementRemoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementWhereRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_element_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementWhereResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_group_element_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_group_element_proto_goTypes,
		DependencyIndexes: file_proto_group_element_proto_depIdxs,
		MessageInfos:      file_proto_group_element_proto_msgTypes,
	}.Build()
	File_proto_group_element_proto = out.File
	file_proto_group_element_proto_rawDesc = nil
	file_proto_group_element_proto_goTypes = nil
	file_proto_group_element_proto_depIdxs = nil
}
